Rest/urls.py
from django.urls import path
from . import views


app_name = 'rest'

urlpatterns = [
    path('students/', views.studentView, name='students'),
    path('students/detail/<str:pk>/', views.studentDetail, name='student-detail'),

    path('students-create/', views.studentCreate, name='student-create'),
    path('students-update/<str:pk>/', views.studentUpdate, name='student-update'),
    path('students-delete/<str:pk>/', views.studentDelete, name='student-delete'),

]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('leads/', include('main.urls', namespace="leads")),

    path('api/', include('Rest.urls', namespace="rest")),

    path('account/', include('account.urls', namespace="account")),

]

main/urls.py
from django.urls import path
from . import views

app_name = "leads"

urlpatterns = [
    path('', views.Lead_list, name="leadList"),
    path('create/', views.Lead_create, name="leadCreate"),
    path('detail/<int:pk>/', views.Lead_detail, name="leadDetail"),
    path('<int:pk>/update/', views.Lead_update, name="leadUpdate"),
    path('<int:pk>/delete/', views.Lead_delete, name="leadDelete"),

]

Rest/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=20)
    roll = models.IntegerField()
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name

account/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    
    def __str__(self):
        return self.user.email


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
        

main/forms.py
from django import forms
from .models import Lead

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )
        

Rest/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Student
from .serializers import StudentSerializer

# Create your views here.


@api_view(['GET'])
def studentView(request):
    students = Student.objects.all()
    serialize = StudentSerializer(students, many=True)

    return Response(serialize.data)


@api_view(['GET'])
def studentDetail(request, pk):
    students = Student.objects.get(id=pk)
    serialize = StudentSerializer(students, many=False)

    return Response(serialize.data)


@api_view(['POST'])
def studentCreate(request):
    serializer = StudentSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()

    return Response(serializer.data)


@api_view(['POST'])
def studentUpdate(request, pk):
    student = Student.objects.get(id=pk)
    serializer = StudentSerializer(instance=student, data=request.data)

    if serializer.is_valid():
        serializer.save()

    return Response(serializer.data)


@api_view(['DELETE'])
def studentDelete(request, pk):
    student = Student.objects.get(id=pk)
    student.delete()

    return Response("Student information deleted successfully.")

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        user = User.objects.create(username=username, email=email, password1=password1, first_name=first_name, last_name=last_name)
        user.save()

        return redirect('leads:leadList')

    return render(request, 'account/register.html')

main/views.py
from django.shortcuts import render, redirect
from .models import Lead
from .forms import LeadModelForm


# Create your views here.
def Lead_list(request):
    leads = Lead.objects.all()
    context = {
        "leads":leads,
    }
    return render(request, "Leads/leads_list.html", context)
    

def Lead_detail(request, pk):
    details = Lead.objects.get(pk=pk)
    context = {
        "details":details,
    }
    return render(request, "Leads/lead_detail.html", context)


def Lead_create(request):
    form = LeadModelForm()
    if request.method == 'POST':
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('leads:leadList')

    context = {
        "form":form,
    }
    return render(request, "Leads/lead_create.html", context)


def Lead_update(request, pk):
    lead = Lead.objects.get(pk=pk)
# this instance=lead means lead took from line 37 which refers to the get(pk=pk)
    form = LeadModelForm(instance=lead)
    if request.method == 'POST':
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("leads:leadList")
    context = {
        "lead":lead,
        "form":form,
    }
    return render(request, "Leads/lead_update.html", context)


def Lead_delete(request, pk):
    lead = Lead.objects.get(pk=pk)
    if request.method == 'POST':
        lead.delete()
        return redirect("leads:leadList")
    return render(request, "Leads/lead_delete.html", {"lead": lead})

templates/Leads/lead_create.html
{% extends "base.html" %}

{% block title %}
    CRM | Create
{% endblock title %}

{% block content %}
    <div class="container">
        <h2>create a lead here...</h2>
        <p>
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>
        </p>
    </div>

{% endblock content %}

</body>
</html>

templates/Leads/lead_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <p> Are you sure, you want to delete the lead "{{lead}}"? </p>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
        <a href=" {{request.META.HTTP_REFERER}} "><button>Cancel</button></a>
    </div>
{% endblock content %}

templates/Leads/lead_detail.html
{% extends "base.html" %}

{% block title %}
    CRM | Detail
{% endblock title %}

{% block content %}

    <hr>
    <div class="container">
        <h3> Details of <b>{{details.first_name}} {{details.last_name}}</b> </h3>
        <p class="container">
            age of the lead: {{details.age}} <br>
            agent of the lead: <b>{{details.agent}}</b> <br>
            last updated: {{details.updated_at}} <br>
        </p>
        <hr>
        <a href=" {% url 'leads:leadUpdate' details.pk %} "><button> update lead </button></a>
        <a href=" {% url 'leads:leadDelete' details.pk %} "><button> delete lead </button></a>
    </div>
{% endblock content %}

</body>
</html>

templates/Leads/lead_update.html
{% extends "base.html" %}

{% block title %}
    CRM | Update
{% endblock title %}

{% block content %}

    <div class="container">
        <h2>Update lead {{lead.first_name}} {{lead.last_name}} </h2>
        <a href="{{request.META.HTTP_REFERER}}"><button>cancel</button></a>
        <p>
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>
        </p>
    </div>

{% endblock content %}

</body>
</html>

templates/Leads/leads_list.html
{% extends "base.html" %}

{% block title %}
    CRM | List
{% endblock title %}

{% block content %}

    <div class="container">
        <h2> All leads list </h2>
        <p>
        <ol class="list-group list-group-numbered">
            {% for lead in leads %}
                <li class="list-group-item"><a href="{% url 'leads:leadDetail' lead.pk %}">{{lead.first_name}} {{lead.last_name}}</a></li>
            {% endfor %}
        </ol>
        </p>
    </div>
{% endblock content %}

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>{% block title %} {% endblock title %}</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'leads:leadList' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'leads:leadCreate' %}">Create a lead</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Agents</a></li>
              <li><a class="dropdown-divider" href="#"></a>More</li>
              <li><a class="dropdown-item" href="#">Category</a></li>
              <li><a class="dropdown-item" href="#">Logout</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


    {% block content %}
      <div class="container"> </div>
    {% endblock content %}


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

  </body>
</html>